global:
  evaluation_interval: 30s
  scrape_interval: 5s
scrape_configs:
  - job_name: data-transfer
    static_configs:
      - targets:
        - 'api:8081'
  - job_name: jaeger
    static_configs:
      - targets:
          - 'jaeger:8889'
